### ISSUE TITLE
Gestion de plusieurs diaporamas différents

### ISSUE THREAD

**Issue by pulkomandy** [Pluxopolis/plxMyCoinSlider#2]
Bonjour,

Je suis en train de réaliser un site pour une école de musique. Je voudrais inclure plusieurs diaporamas dans des pages statiques (1 pour la danse, 1 pour la musique, etc). Cependant cela ne semble pas possible avec plxMyCoinSlider pour le moment.

Est-ce qu'une gestion de plusieurs diaporamas indépendants pourrait être ajoutée?

**Comment by Pluxopolis** [comment]
Bonjour

plxMyCoinSlider peut être utiliser dans une page statique (cf écran d'aide)

> Affichage du diaporama dans une page statique
> - éditer le contenu d'une page statique et allant dans la gestion des pages statiques: menu "Pages Statiques" dans l'administration
> - ajouter les lignes suivantes à l'endroit où vous souhaitez afficher le diaporama

```
<?php
global $plxShow;
eval($plxShow->callHook("MyCoinSlider"));
?>
```

**Comment by pulkomandy** [comment]
Oui, cependant dans ce cas toutes mes pages statiques affichent les mêmes images. Je voudrais, dans chaque page statique ou le slider est utilisé, un jeu d'image différents :)

**Comment by Pluxopolis** [comment]
En effet. Malheureusement MyCoinSlider ne gère qu'un seul diaporama. J'ai peur que ce ne soit pas le bon plugin pour répondre au besoin. Il faudrait aller voir sur le forum de PluXml (rubrique Plugins) s'il n'y a pas un autre plugin.Il existe des plugins pour afficher des galeries d'images. Ils seront certainement mieux adaptés.

**Comment by pulkomandy** [comment]
J'ai bricolé une solution comme ceci:


        public function MyCoinSlider($filter) {

                echo "\n<div id=\"coin-slider\">\n";
                foreach($this->coinslider->aSlides as $slide) {
                        if($slide['active'] && (($slide['onclick'] == $filter) || ($filter == ''))) {
                                $onclick = $slide['url'];
                                echo '<a href="'.plxUtils::strCheck($onclick).'"><img alt="" src="'.plxUtils::strCheck($slide['url']).'" title="'.plxUtils::strCheck($slide['title']).'" /><span>'.strip_tags($slide['description'], '<strong><b><em><br>')."</span></a>\n";
                        }
                }
                echo "</div>\n";

        }

J'abuse de l'attribut "onclick" des images pour l'utiliser comme un filtre (et j'ai supprimé son utilisation normale).

Le résultat est visible sur: http://emda.tk
